# Generated by Django 4.1.7 on 2023-04-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='poll_text',
            new_name='title',
        ),
    ]
