# Generated by Django 4.1.7 on 2023-03-27 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='date_pub',
        ),
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 27, 7, 46, 44, 628479, tzinfo=datetime.timezone.utc)),
        ),
    ]
