# Generated by Django 4.1.7 on 2023-05-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
