# Generated by Django 4.1.7 on 2023-04-16 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_poll_text_poll_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('poll_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.poll')),
                ('many_answers', models.BooleanField()),
            ],
            bases=('polls.poll',),
        ),
        migrations.AlterField(
            model_name='poll',
            name='can_revote',
            field=models.BooleanField(default=False),
        ),
    ]
