# Generated by Django 4.1.7 on 2023-04-17 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_quiz_alter_poll_can_revote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='can_revote',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.poll'),
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
